baseURL = "https://pythrick.github.io"
languageCode = "en"
DefaultContentLanguage = "pt"
title = "Website do Patrick Rodrigues"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Patrick Rodrigues"
author = "Patrick Rodrigues"
description = "Python Live Coder"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/pythrick"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/pythrick"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/pythrick"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:pythrick@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

